import os
import asyncio
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")

TWILIO_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.environ.get("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")


async def send_notifications(email: str, phone: str, name: str, score_data: dict, narrative: str):
    """Send email and WhatsApp — each logged individually so failures are visible"""
    if email and SMTP_USER:
        try:
            await _send_email(email, name, score_data, narrative)
            print(f"[Email] Sent to {email}")
        except Exception as e:
            print(f"[Email] FAILED: {e}")

    if phone and TWILIO_SID:
        try:
            await _send_whatsapp(phone, name, score_data)
        except Exception as e:
            print(f"[WhatsApp] FAILED: {e}")


async def _send_email(to_email: str, name: str, score_data: dict, narrative: str):
    score = score_data["final_score"]
    grade = score_data["grade"]
    recommendation = score_data["recommendation"]

    html = f"""
    <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
      <h1 style="font-size: 28px; color: #1a1a1a; margin-bottom: 4px;">CreditBridge</h1>
      <p style="color: #666; margin-top: 0;">Micro-Loan Credit Assessment</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;">
      <p style="font-size: 16px;">Dear {name},</p>
      <p>Your credit assessment has been completed.</p>
      <div style="background: #f9f9f9; border-left: 4px solid {score_data['grade_color']};
                  padding: 20px 24px; border-radius: 4px; margin: 24px 0;">
        <div style="font-size: 48px; font-weight: bold; color: {score_data['grade_color']};">{score}</div>
        <div style="font-size: 18px; color: #333;">{grade}</div>
        <div style="font-size: 14px; color: #666; margin-top: 8px;">{recommendation}</div>
      </div>
      <h3 style="font-size: 16px; color: #333;">Assessment Summary</h3>
      <p style="line-height: 1.7; color: #444;">{narrative}</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;">
      <p style="font-size: 12px; color: #999;">
        This assessment was generated by CreditBridge using alternative financial data.
        It is intended to assist loan officers and does not constitute a formal credit decision.
      </p>
    </div>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"CreditBridge Assessment — {name}: {score}/850 ({grade})"
    msg["From"] = SMTP_USER
    msg["To"] = to_email
    msg.attach(MIMEText(html, "html"))

    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _smtp_send, msg, to_email)


def _smtp_send(msg, to_email):
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, to_email, msg.as_string())


async def _send_whatsapp(to_phone: str, name: str, score_data: dict):
    from twilio.rest import Client

    score = score_data["final_score"]
    grade = score_data["grade"]
    recommendation = score_data["recommendation"]

    body = (
        f"*CreditBridge Assessment*\n\n"
        f"Applicant: {name}\n"
        f"Score: *{score}/850* ({grade})\n"
        f"Verdict: {recommendation}\n\n"
        f"Full report sent to email."
    )

    to_whatsapp = f"whatsapp:{to_phone}" if not to_phone.startswith("whatsapp:") else to_phone

    print(f"[WhatsApp] Sending to {to_whatsapp} from {TWILIO_WHATSAPP_FROM}")
    print(f"[WhatsApp] SID present: {bool(TWILIO_SID)}, Token present: {bool(TWILIO_TOKEN)}")

    loop = asyncio.get_event_loop()

    def _call():
        client = Client(TWILIO_SID, TWILIO_TOKEN)
        msg = client.messages.create(
            body=body,
            from_=TWILIO_WHATSAPP_FROM,
            to=to_whatsapp
        )
        print(f"[WhatsApp] Sent — SID: {msg.sid}, Status: {msg.status}")
        return msg

    await loop.run_in_executor(None, _call)
